import type { SectionMeta } from '@/lib/questionnaire/types';

export const investmentStrategySection: SectionMeta = {
  key: 'investment_strategy',
  order: 5,
  title: 'Section V: Investment Strategy',
  helper:
    'Provide stage mix (%), sizing, diversification, Jamaica floor, returns, instruments, fees, co-investors, and thesis. Upload portfolio projection workbook.',
  questions: [
    {
      key: 'stage_allocation',
      label: 'Stage allocation (% of fund commitment)',
      type: 'stage_allocation',
      required: true,
      helper: 'Ideas / startups / scaling / mature must total 100%.',
    },
    {
      key: 'company_size_params',
      label: 'Company size — revenue and investment per company (USD)',
      type: 'company_size_params',
      required: true,
    },
    {
      key: 'investment_rounds',
      label: 'Investment rounds — min / max per round (USD)',
      type: 'structured_list',
      listKind: 'investment_rounds',
      addLabel: '+ Add round',
      required: false,
    },
    {
      key: 'sector_allocations',
      label: 'Sector allocations',
      type: 'structured_list',
      listKind: 'sector_allocations',
      addLabel: '+ Add sector',
      required: true,
      helper: 'Each row: sector name and maximum % of the portfolio.',
    },
    {
      key: 'geographic_allocations',
      label: 'Geographic allocations',
      type: 'structured_list',
      listKind: 'geographic_allocations',
      addLabel: '+ Add region / country',
      required: false,
    },
    {
      key: 'jamaica_min_allocation_pct',
      label: 'Jamaica minimum allocation',
      type: 'number',
      required: true,
      helper: 'Minimum % of fund allocated to Jamaica (DBJ requires minimum 40%).',
    },
    {
      key: 'other_diversification_params',
      label: 'Other diversification parameters',
      type: 'textarea',
      rows: 3,
      required: false,
    },
    {
      key: 'other_investment_params',
      label: 'Other investment parameters',
      type: 'textarea',
      rows: 3,
      required: false,
    },
    {
      key: 'control_policy',
      label: 'Control policy',
      type: 'select',
      options: [
        { value: 'controlling', label: 'Controlling stakes' },
        { value: 'minority', label: 'Minority stakes' },
        { value: 'flexible', label: 'Flexible' },
      ],
      required: true,
    },
    {
      key: 'protection_clauses',
      label: 'Protection clauses',
      type: 'textarea',
      rows: 4,
      required: true,
    },
    {
      key: 'gross_irr_target_pct',
      label: 'Gross IRR target (% p.a.)',
      type: 'number',
      required: true,
    },
    {
      key: 'net_irr_target_pct',
      label: 'Net IRR target (% p.a.)',
      type: 'number',
      required: true,
    },
    {
      key: 'investment_horizon_years',
      label: 'Investment horizon (years)',
      type: 'number',
      required: true,
    },
    {
      key: 'investment_instruments',
      label: 'Investment instruments',
      type: 'structured_list',
      listKind: 'investment_instruments',
      addLabel: '+ Add instrument',
      required: true,
      helper: 'Instrument, approximate % of fund, and legal notes. Order reflects priority.',
    },
    {
      key: 'charges_portfolio_fees',
      label: 'Does the fund charge portfolio-level fees?',
      type: 'boolean',
      required: true,
    },
    {
      key: 'portfolio_fees_description',
      label: 'Portfolio fees — description',
      type: 'textarea',
      rows: 3,
      required: false,
    },
    {
      key: 'coinvestment_reliance',
      label: 'Reliance on co-investment',
      type: 'select',
      options: [
        { value: 'required', label: 'Required' },
        { value: 'opportunistic', label: 'Opportunistic' },
        { value: 'none', label: 'None' },
      ],
      required: true,
    },
    {
      key: 'coinvestment_steps',
      label: 'Co-investment process / steps',
      type: 'textarea',
      rows: 4,
      required: false,
    },
    {
      key: 'coinvestors',
      label: 'Known or target co-investors',
      type: 'structured_list',
      listKind: 'coinvestors',
      addLabel: '+ Add co-investor',
      required: false,
    },
    {
      key: 'investment_thesis',
      label: 'Investment Thesis',
      type: 'textarea',
      rows: 8,
      required: true,
      helper:
        'Explain the rationale for creating this fund. Cover: why the opportunity exists, why these sectors were chosen, why this geographic area, why the timing is right, and cite any supporting research or studies.',
    },
    {
      key: 'portfolio_projection_excel',
      label: 'Portfolio projection (Excel upload)',
      type: 'file',
      required: true,
      uploadTag: 'portfolio_projection',
    },
  ],
};
