import type { SectionMeta } from '@/lib/questionnaire/types';

export const sponsorSection: SectionMeta = {
  key: 'sponsor',
  order: 2,
  title: 'Section II: Sponsor / Fund Manager details',
  helper:
    'Describe the manager entity, governance, conflicts, track record, and financial strength. Upload the organisation chart and recent financial statements where indicated.',
  questions: [
    { key: 'manager_name', label: 'Manager name', type: 'text', required: true },
    {
      key: 'shareholders',
      label: 'Shareholders',
      type: 'structured_list',
      listKind: 'shareholders',
      required: true,
      addLabel: 'Add Shareholder',
      helper: 'Add each shareholder with their occupation.',
    },
    {
      key: 'investment_professionals',
      label: 'Investment professionals',
      type: 'structured_list',
      listKind: 'investment_professionals',
      required: true,
      addLabel: 'Add Investment Professional',
      footnote: 'Full bios are completed here (Investment professionals & Support staff).',
    },
    {
      key: 'support_staff',
      label: 'Support staff',
      type: 'structured_list',
      listKind: 'support_staff',
      required: false,
      addLabel: 'Add Support Staff',
    },
    {
      key: 'outside_advisors',
      label: 'Outside advisors & committee members',
      type: 'structured_list',
      listKind: 'outside_advisors',
      required: false,
      addLabel: 'Add Advisor / Committee Member',
    },
    {
      key: 'office_locations',
      label: 'Office locations',
      type: 'structured_list',
      listKind: 'office_locations',
      required: true,
      addLabel: 'Add Office Location',
    },
    {
      key: 'manager_will_invest',
      label: 'Will the manager invest in the fund?',
      type: 'boolean',
      required: true,
    },
    {
      key: 'manager_investment_amount',
      label: 'Manager investment amount (USD)',
      type: 'currency',
      required: false,
    },
    {
      key: 'manager_investment_pct',
      label: 'Manager investment (% of total fund)',
      type: 'number',
      required: false,
    },
    {
      key: 'manager_investment_method',
      label: 'How will investment be made?',
      type: 'textarea',
      rows: 2,
      required: false,
    },
    {
      key: 'compensation_structure',
      label: 'Compensation structure (salary, bonus, carried interest)',
      type: 'textarea',
      rows: 4,
      required: true,
    },
    {
      key: 'outsourced_services',
      label: 'Outsourced services',
      type: 'structured_list',
      listKind: 'outsourced_services',
      required: false,
      addLabel: 'Add Outsourced Service',
      helper: 'Company or provider name, activities, annual cost (USD), and who pays.',
    },
    {
      key: 'other_business_activities_yes',
      label: 'Does the manager have other business activities?',
      type: 'boolean',
      required: true,
    },
    {
      key: 'other_activities',
      label: 'Describe other activities',
      type: 'textarea',
      rows: 3,
      required: false,
    },
    {
      key: 'outside_contracts_yes',
      label: 'Are there any outside contracts?',
      type: 'boolean',
      required: true,
    },
    {
      key: 'outside_contracts',
      label: 'Describe contracts and liabilities',
      type: 'textarea',
      rows: 3,
      required: false,
    },
    {
      key: 'has_conflicts_of_interest',
      label: 'Are there any conflicts of interest?',
      type: 'boolean',
      required: true,
    },
    {
      key: 'conflicts_description',
      label: 'Describe the conflicts of interest',
      type: 'textarea',
      rows: 3,
      required: false,
    },
    {
      key: 'conflicts_resolution',
      label: 'Resolution procedures',
      type: 'textarea',
      rows: 3,
      required: false,
    },
    {
      key: 'has_regulations',
      label: 'Is the manager subject to any regulations?',
      type: 'boolean',
      required: true,
    },
    {
      key: 'regulations_list',
      label: 'List all applicable regulations',
      type: 'textarea',
      rows: 3,
      required: false,
    },
    {
      key: 'compliance_status',
      label: 'Compliance status',
      type: 'select',
      required: false,
      options: [
        { value: 'compliant', label: 'Fully compliant' },
        { value: 'pending', label: 'Pending compliance' },
        { value: 'non_compliant', label: 'Non-compliant' },
      ],
    },
    {
      key: 'compliance_details',
      label: 'Compliance details',
      type: 'textarea',
      rows: 2,
      required: false,
    },
    {
      key: 'has_litigation',
      label: 'Any litigation or regulatory investigations?',
      type: 'boolean',
      required: true,
    },
    {
      key: 'litigation_status',
      label: 'Matter status',
      type: 'select',
      required: false,
      options: [
        { value: 'past', label: 'Past (resolved)' },
        { value: 'pending', label: 'Pending (ongoing)' },
      ],
    },
    {
      key: 'litigation_description',
      label: 'Description of matter',
      type: 'textarea',
      rows: 3,
      required: false,
    },
    {
      key: 'track_record_vc_pe',
      label: 'Track record — VC/PE experience, performance, impact indicators',
      type: 'textarea',
      rows: 6,
      maxWords: 400,
      required: true,
    },
    {
      key: 'financial_strength_evidence',
      label: 'Financial data — evidence of financial strength',
      type: 'textarea',
      rows: 4,
      required: true,
    },
    {
      key: 'org_chart',
      label: 'Organisation chart (upload)',
      type: 'file',
      required: true,
      uploadTag: 'org_chart',
    },
    {
      key: 'financial_statements',
      label: 'Financial statements (upload)',
      type: 'file',
      required: true,
      uploadTag: 'financial_statements',
    },
  ],
};
