BEGIN;

CREATE TABLE IF NOT EXISTS public.ref_countries (
  code text PRIMARY KEY CHECK (char_length(code) = 2 AND code = upper(code)),
  name text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_ref_countries_name ON public.ref_countries (name);

ALTER TABLE public.ref_countries ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS ref_countries_select_authenticated ON public.ref_countries;
CREATE POLICY ref_countries_select_authenticated
  ON public.ref_countries
  FOR SELECT
  TO authenticated
  USING (true);

INSERT INTO public.ref_countries (code, name, sort_order)
VALUES
('AF','Afghanistan',1),
('AX','Åland Islands',2),
('AL','Albania',3),
('DZ','Algeria',4),
('AS','American Samoa',5),
('AD','Andorra',6),
('AO','Angola',7),
('AI','Anguilla',8),
('AQ','Antarctica',9),
('AG','Antigua and Barbuda',10),
('AR','Argentina',11),
('AM','Armenia',12),
('AW','Aruba',13),
('AU','Australia',14),
('AT','Austria',15),
('AZ','Azerbaijan',16),
('BS','Bahamas',17),
('BH','Bahrain',18),
('BD','Bangladesh',19),
('BB','Barbados',20),
('BY','Belarus',21),
('BE','Belgium',22),
('BZ','Belize',23),
('BJ','Benin',24),
('BM','Bermuda',25),
('BT','Bhutan',26),
('BO','Bolivia, Plurinational State of',27),
('BQ','Bonaire, Sint Eustatius and Saba',28),
('BA','Bosnia and Herzegovina',29),
('BW','Botswana',30),
('BV','Bouvet Island',31),
('BR','Brazil',32),
('IO','British Indian Ocean Territory',33),
('BN','Brunei Darussalam',34),
('BG','Bulgaria',35),
('BF','Burkina Faso',36),
('BI','Burundi',37),
('CV','Cabo Verde',38),
('KH','Cambodia',39),
('CM','Cameroon',40),
('CA','Canada',41),
('KY','Cayman Islands',42),
('CF','Central African Republic',43),
('TD','Chad',44),
('CL','Chile',45),
('CN','China',46),
('CX','Christmas Island',47),
('CC','Cocos (Keeling) Islands',48),
('CO','Colombia',49),
('KM','Comoros',50),
('CG','Congo',51),
('CD','Congo, Democratic Republic of the',52),
('CK','Cook Islands',53),
('CR','Costa Rica',54),
('CI','Côte d''Ivoire',55),
('HR','Croatia',56),
('CU','Cuba',57),
('CW','Curaçao',58),
('CY','Cyprus',59),
('CZ','Czechia',60),
('DK','Denmark',61),
('DJ','Djibouti',62),
('DM','Dominica',63),
('DO','Dominican Republic',64),
('EC','Ecuador',65),
('EG','Egypt',66),
('SV','El Salvador',67),
('GQ','Equatorial Guinea',68),
('ER','Eritrea',69),
('EE','Estonia',70),
('SZ','Eswatini',71),
('ET','Ethiopia',72),
('FK','Falkland Islands (Malvinas)',73),
('FO','Faroe Islands',74),
('FJ','Fiji',75),
('FI','Finland',76),
('FR','France',77),
('GF','French Guiana',78),
('PF','French Polynesia',79),
('TF','French Southern Territories',80),
('GA','Gabon',81),
('GM','Gambia',82),
('GE','Georgia',83),
('DE','Germany',84),
('GH','Ghana',85),
('GI','Gibraltar',86),
('GR','Greece',87),
('GL','Greenland',88),
('GD','Grenada',89),
('GP','Guadeloupe',90),
('GU','Guam',91),
('GT','Guatemala',92),
('GG','Guernsey',93),
('GN','Guinea',94),
('GW','Guinea-Bissau',95),
('GY','Guyana',96),
('HT','Haiti',97),
('HM','Heard Island and McDonald Islands',98),
('VA','Holy See',99),
('HN','Honduras',100),
('HK','Hong Kong',101),
('HU','Hungary',102),
('IS','Iceland',103),
('IN','India',104),
('ID','Indonesia',105),
('IR','Iran, Islamic Republic of',106),
('IQ','Iraq',107),
('IE','Ireland',108),
('IM','Isle of Man',109),
('IL','Israel',110),
('IT','Italy',111),
('JM','Jamaica',112),
('JP','Japan',113),
('JE','Jersey',114),
('JO','Jordan',115),
('KZ','Kazakhstan',116),
('KE','Kenya',117),
('KI','Kiribati',118),
('KP','Korea, Democratic People''s Republic of',119),
('KR','Korea, Republic of',120),
('KW','Kuwait',121),
('KG','Kyrgyzstan',122),
('LA','Lao People''s Democratic Republic',123),
('LV','Latvia',124),
('LB','Lebanon',125),
('LS','Lesotho',126),
('LR','Liberia',127),
('LY','Libya',128),
('LI','Liechtenstein',129),
('LT','Lithuania',130),
('LU','Luxembourg',131),
('MO','Macao',132),
('MG','Madagascar',133),
('MW','Malawi',134),
('MY','Malaysia',135),
('MV','Maldives',136),
('ML','Mali',137),
('MT','Malta',138),
('MH','Marshall Islands',139),
('MQ','Martinique',140),
('MR','Mauritania',141),
('MU','Mauritius',142),
('YT','Mayotte',143),
('MX','Mexico',144),
('FM','Micronesia, Federated States of',145),
('MD','Moldova, Republic of',146),
('MC','Monaco',147),
('MN','Mongolia',148),
('ME','Montenegro',149),
('MS','Montserrat',150),
('MA','Morocco',151),
('MZ','Mozambique',152),
('MM','Myanmar',153),
('NA','Namibia',154),
('NR','Nauru',155),
('NP','Nepal',156),
('NL','Netherlands, Kingdom of the',157),
('NC','New Caledonia',158),
('NZ','New Zealand',159),
('NI','Nicaragua',160),
('NE','Niger',161),
('NG','Nigeria',162),
('NU','Niue',163),
('NF','Norfolk Island',164),
('MK','North Macedonia',165),
('MP','Northern Mariana Islands',166),
('NO','Norway',167),
('OM','Oman',168),
('PK','Pakistan',169),
('PW','Palau',170),
('PS','Palestine, State of',171),
('PA','Panama',172),
('PG','Papua New Guinea',173),
('PY','Paraguay',174),
('PE','Peru',175),
('PH','Philippines',176),
('PN','Pitcairn',177),
('PL','Poland',178),
('PT','Portugal',179),
('PR','Puerto Rico',180),
('QA','Qatar',181),
('RE','Réunion',182),
('RO','Romania',183),
('RU','Russian Federation',184),
('RW','Rwanda',185),
('BL','Saint Barthélemy',186),
('SH','Saint Helena, Ascension and Tristan da Cunha',187),
('KN','Saint Kitts and Nevis',188),
('LC','Saint Lucia',189),
('MF','Saint Martin (French part)',190),
('PM','Saint Pierre and Miquelon',191),
('VC','Saint Vincent and the Grenadines',192),
('WS','Samoa',193),
('SM','San Marino',194),
('ST','Sao Tome and Principe',195),
('SA','Saudi Arabia',196),
('SN','Senegal',197),
('RS','Serbia',198),
('SC','Seychelles',199),
('SL','Sierra Leone',200),
('SG','Singapore',201),
('SX','Sint Maarten (Dutch part)',202),
('SK','Slovakia',203),
('SI','Slovenia',204),
('SB','Solomon Islands',205),
('SO','Somalia',206),
('ZA','South Africa',207),
('GS','South Georgia and the South Sandwich Islands',208),
('SS','South Sudan',209),
('ES','Spain',210),
('LK','Sri Lanka',211),
('SD','Sudan',212),
('SR','Suriname',213),
('SJ','Svalbard and Jan Mayen',214),
('SE','Sweden',215),
('CH','Switzerland',216),
('SY','Syrian Arab Republic',217),
('TW','Taiwan, Province of China',218),
('TJ','Tajikistan',219),
('TZ','Tanzania, United Republic of',220),
('TH','Thailand',221),
('TL','Timor-Leste',222),
('TG','Togo',223),
('TK','Tokelau',224),
('TO','Tonga',225),
('TT','Trinidad and Tobago',226),
('TN','Tunisia',227),
('TR','Türkiye',228),
('TM','Turkmenistan',229),
('TC','Turks and Caicos Islands',230),
('TV','Tuvalu',231),
('UG','Uganda',232),
('UA','Ukraine',233),
('AE','United Arab Emirates',234),
('GB','United Kingdom of Great Britain and Northern Ireland',235),
('UM','United States Minor Outlying Islands',236),
('US','United States of America',237),
('UY','Uruguay',238),
('UZ','Uzbekistan',239),
('VU','Vanuatu',240),
('VE','Venezuela, Bolivarian Republic of',241),
('VN','Viet Nam',242),
('VG','Virgin Islands (British)',243),
('VI','Virgin Islands (U.S.)',244),
('WF','Wallis and Futuna',245),
('EH','Western Sahara',246),
('YE','Yemen',247),
('ZM','Zambia',248),
('ZW','Zimbabwe',249)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order;

COMMIT;
